apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: {{ .Values.secrets.type }}
data:
  {{- range $k, $v := .Values.secret_env }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}